api_platform:
    title: Identiplante API
    description: API pour l'outil Identiplante
    version: 2.0.0
    openapi:
        contact:
            name: "Contact"
            url: "https://www.tela-botanica.org/appli:identiplante"
            email: "identiplante_remarques@tela-botanica.org"
    formats:
        jsonld: ['application/ld+json']
        json: [ 'application/json' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    collection:
        pagination:
            enabled: false
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' , '%kernel.project_dir%/src/Dto' ]