monolog:
    handlers:
        main:
            action_level: error
            handler: nested
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
